### ISSUE TITLE
Cannot include custom/modified timers for particular server

### ISSUE THREAD

**Issue by johannes-cabal** [victorgawk/yellowtracker#1]
Hiya!

Been exploring some various discord bots and really like the one you've put together. The only issue is that the server I'm playing on has different timers than obviously what you see in Talon.

Would it be possible to receive instructions on either self-hosting in a container and/or droplet OR being able to ingest some custom MVP or the ability to change the timers to "custom" and require inputs for those variables? 

Thanks.

**Comment by victorgawk** [comment]
Hello. @johannes-cabal 
This will require a certain effort to be implemented. The bot already got the most common MVPs with their official times. Another problem is that the bot instance is hosted with very limited resources. Not sure about the impact if everyone start to add their own MVPs. I recommend that you run another instance and modify the MVP and times by yourself.
