### ISSUE TITLE
The tracker is offline

### ISSUE THREAD

**Issue by VanjiRiven** [victorgawk/yellowtracker#2]
It no longer works? can you atleast update the sourcefile please?

**Comment by victorgawk** [comment]
> It no longer works?

Yeah I took it offline.

> can you alteast update the sourcefile please?

The sourcefiles are up to date.

**Comment by VanjiRiven** [comment]
> > It no longer works?
> 
> Yeah I took it offline.
> 
> > can you alteast update the sourcefile please?
> 
> The sourcefiles are up to date.

It is? Then am i doing something wrong? I just need to put my token and it should work right?

**Comment by victorgawk** [comment]
You can see how to run a local instance on `README.md` (https://github.com/victorgawk/yellowtracker/blob/master/README.md).

**Comment by fajarbgs** [comment]
Hello, i tried to run it via replit, but this message shows up

`python bot.py
/home/runner/yellowtracker/venv/bin/python: can't open file 'bot.py': [Errno 2] No such file or directory
exit status 2`

**Comment by fajarbgs** [comment]
Hello excuse me, sorry if this dumb question. I am just newb to coding. Can I run this in replit + uptimerobot to make it live? and what should I consider if I run it through replit?

**Comment by victorgawk** [comment]
> Hello excuse me, sorry if this dumb question. I am just newb to coding. Can I run this in replit + uptimerobot to make it live? and what should I consider if I run it through replit?

Honestly, I don't know... I never heard any of these before. You can see how to run a local instance on `README.md` (https://github.com/victorgawk/yellowtracker/blob/master/README.md).

**Comment by fajarbgs** [comment]
> > Hello excuse me, sorry if this dumb question. I am just newb to coding. Can I run this in replit + uptimerobot to make it live? and what should I consider if I run it through replit?
> 
> Honestly, I don't know... I never heard any of these before. You can see how to run a local instance on `README.md` (https://github.com/victorgawk/yellowtracker/blob/master/README.md).

I didn't quite understand the part of PostgreSQL, can you give me a little guide or example?

**Comment by victorgawk** [comment]
PostgreSQL is a relational database (basically a place to store data). Official link: https://www.postgresql.org/
It is used to store:
- which channel the MVP tracker was activated
- the MVP respawn times
- etc

**Comment by fajarbgs** [comment]
![image](https://user-images.githubusercontent.com/41311829/200086603-582dd28d-6165-4301-8308-81e1d86b2eb2.png)
can I just edit in yellowtracker.sql?

**Comment by victorgawk** [comment]
No. This file is used on the database to create tables and insert the MVP info in a table called `mvp`. The application does not load data directly from this file. Instead it loads from the tables in the database.

**Comment by victorgawk** [comment]
I am keeping one instance online again. Link available on: https://github.com/victorgawk/yellowtracker#usage
