### ISSUE TITLE
The Timer Doesn't seem to move / update

### ISSUE THREAD

**Issue by VanjiRiven** [victorgawk/yellowtracker#4]
Hello VictorGawk , These Occured like 2 days ago , I was waiting for it to move again Because I thought It was just some sort of maintenance or I thought You were fixing / updating the timer. So I would Like to Know if There's a Problem With the timer Or You just didn't Know about the issue

**Comment by victorgawk** [comment]
Thanks for reporting this issue. Noted the problem, the timers aren't being updated. For now I will restart the instance. No idea what caused the problem yet.

EDIT: Restarted the instance but no success yet.

**Comment by victorgawk** [comment]
Timers fixed.
